update checks.yml for xray scan

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -12,61 +12,61 @@ env:
   GIT_TAG: ${{ github.sha }}
 
 jobs:
-  codeql:
-    name: codeql
-    runs-on: ubuntu-latest
-    permissions:
-      actions: read
-      contents: read
-      security-events: write
-    strategy:
-      fail-fast: false
-      matrix:
-        language: [ 'java' ]
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Initialize CodeQL
-        uses: github/codeql-action/init@v2
-        with:
-          languages: ${{ matrix.language }}
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-      - name: Build with Gradle
-        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
-        with:
-          arguments: build
-      - run: mkdir codeql
-      - name: Perform CodeQL Analysis
-        uses: github/codeql-action/analyze@v2
-        with:
-          output: ./codeql
-          upload: false
-      - run: |
-          cat ./codeql/java.sarif
-      - name: Publish report to defectdojo
-        id: import-scan
-        uses: ivanamat/defectdojo-import-scan@v1
-        with:
-          token: ${{ secrets.DEFECTOJO_TOKEN }}
-          defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
-          engagement: ${{ secrets.ENGAGEMENT }}
-          product_name: ${{ secrets.PRODUCT_NAME }}
-          file: ./codeql/java.sarif
-          scan_type: SARIF
-          test_title: Codeql Scan
-          tags: codeql
-          skip_duplicates: true
-          close_old_findings: true
-          branch_tag: main
-          build_id: ${{ github.run_id }}
-          commit_hash: ${{ github.sha }}
-      - name: Show response of defectdojo
-        run: |
-          echo ${{ steps.import-scan.outputs.response }}
+  # codeql:
+  #   name: codeql
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     actions: read
+  #     contents: read
+  #     security-events: write
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       language: [ 'java' ]
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+  #     - name: Initialize CodeQL
+  #       uses: github/codeql-action/init@v2
+  #       with:
+  #         languages: ${{ matrix.language }}
+  #     - name: Set up JDK 17
+  #       uses: actions/setup-java@v2
+  #       with:
+  #         java-version: '17'
+  #         distribution: 'temurin'
+  #     - name: Build with Gradle
+  #       uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
+  #       with:
+  #         arguments: build
+  #     - run: mkdir codeql
+  #     - name: Perform CodeQL Analysis
+  #       uses: github/codeql-action/analyze@v2
+  #       with:
+  #         output: ./codeql
+  #         upload: false
+  #     - run: |
+  #         cat ./codeql/java.sarif
+  #     - name: Publish report to defectdojo
+  #       id: import-scan
+  #       uses: ivanamat/defectdojo-import-scan@v1
+  #       with:
+  #         token: ${{ secrets.DEFECTOJO_TOKEN }}
+  #         defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
+  #         engagement: ${{ secrets.ENGAGEMENT }}
+  #         product_name: ${{ secrets.PRODUCT_NAME }}
+  #         file: ./codeql/java.sarif
+  #         scan_type: SARIF
+  #         test_title: Codeql Scan
+  #         tags: codeql
+  #         skip_duplicates: true
+  #         close_old_findings: true
+  #         branch_tag: main
+  #         build_id: ${{ github.run_id }}
+  #         commit_hash: ${{ github.sha }}
+  #     - name: Show response of defectdojo
+  #       run: |
+  #         echo ${{ steps.import-scan.outputs.response }}
 #  dependency-check:
 #    name: dependency-check
 #    runs-on: ubuntu-latest
@@ -190,43 +190,43 @@ jobs:
 #         run: |
 #           set -e
 #           printf '%s\n' '${{ steps.import-scan.outputs.response }}'
-  snyk-scan:
-    name: snyk-scan
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    steps:
-      - uses: actions/checkout@v2
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions/gradle@master
-        continue-on-error: true # To make sure that SARIF upload gets called
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          args: --sarif-file-output=snyk.sarif
-      - name: Publish report to defectdojo
-        id: import-scan
-        uses: ivanamat/defectdojo-import-scan@v1
-        with:
-          token: ${{ secrets.DEFECTOJO_TOKEN }}
-          defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
-          engagement: ${{ secrets.ENGAGEMENT }}
-          product_name: ${{ secrets.PRODUCT_NAME }}
-          file: snyk.sarif
-          scan_type: SARIF
-          test_title: Snyk Scan
-          tags: snyk
-          skip_duplicates: true
-          close_old_findings: true
-          push_to_jira: false
-          branch_tag: ${{ github.base_ref }}
-          build_id: ${{ github.run_id }}
-          commit_hash: ${{ github.sha }}
-      - name: Show response of defectdojo
-        run: |
-          set -e
-          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
+  # snyk-scan:
+  #   name: snyk-scan
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Run Snyk to check for vulnerabilities
+  #       uses: snyk/actions/gradle@master
+  #       continue-on-error: true # To make sure that SARIF upload gets called
+  #       env:
+  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+  #       with:
+  #         args: --sarif-file-output=snyk.sarif
+  #     - name: Publish report to defectdojo
+  #       id: import-scan
+  #       uses: ivanamat/defectdojo-import-scan@v1
+  #       with:
+  #         token: ${{ secrets.DEFECTOJO_TOKEN }}
+  #         defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
+  #         engagement: ${{ secrets.ENGAGEMENT }}
+  #         product_name: ${{ secrets.PRODUCT_NAME }}
+  #         file: snyk.sarif
+  #         scan_type: SARIF
+  #         test_title: Snyk Scan
+  #         tags: snyk
+  #         skip_duplicates: true
+  #         close_old_findings: true
+  #         push_to_jira: false
+  #         branch_tag: ${{ github.base_ref }}
+  #         build_id: ${{ github.run_id }}
+  #         commit_hash: ${{ github.sha }}
+  #     - name: Show response of defectdojo
+  #       run: |
+  #         set -e
+  #         printf '%s\n' '${{ steps.import-scan.outputs.response }}'
 #   tfsec-scan:
 #     name: tfsec-scan
 #     runs-on: ubuntu-latest
@@ -264,58 +264,75 @@ jobs:
 #         run: |
 #           set -e
 #           printf '%s\n' '${{ steps.import-scan.outputs.response }}'
-#   trivy-scan:
-#     name: trivy-scan
-#     runs-on: ubuntu-latest
-#     permissions:
-#       contents: read
-#       packages: write
-#     steps:
-#       - uses: actions/checkout@v2
-#       - name: Set up JDK 17
-#         uses: actions/setup-java@v2
-#         with:
-#           java-version: '17'
-#           distribution: 'temurin'
-#       - name: Build with Gradle
-#         uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
-#         with:
-#           arguments: build
-#       - name: Build Image
-#         run: |-
-#           pwd
-#           ls -al
-#           docker build  --tag "java_demo:${{ env.GIT_TAG }}" .
-#           docker tag "java_demo:${{ env.GIT_TAG }}" java_demo:1.0
-#         shell: bash
-#       - name: Run Trivy vulnerability scanner
-#         uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
-#         with:
-#           image-ref: java_demo:1.0
-#           format: 'json'
-#           output: 'trivy-results.json'
-#           severity: 'CRITICAL,HIGH'
-#       - name: Publish report to defectdojo
-#         id: import-scan
-#         uses: ivanamat/defectdojo-import-scan@v1
-#         with:
-#           token: ${{ secrets.DEFECTOJO_TOKEN }}
-#           defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
-#           engagement: ${{ secrets.ENGAGEMENT }}
-#           product_name: ${{ secrets.PRODUCT_NAME }}
-#           file: trivy-results.json
-#           scan_type: Trivy Scan
-#           test_title: Trivy Scan
-#           tags: trivy
-#           skip_duplicates: true
-#           close_old_findings: true
-#           push_to_jira: false
-#           branch_tag: ${{ github.base_ref }}
-#           build_id: ${{ github.run_id }}
-#           commit_hash: ${{ github.sha }}
-#       - name: Show response of defectdojo
-#         run: |
-#           echo ${{ steps.import-scan.outputs.response }}
+  xray-scan:
+    name: xray-scan
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+      - name: Build with Gradle
+        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
+        with:
+          arguments: build
+      - name: Build Image
+        run: |-
+          pwd
+          ls -al
+          docker build  --tag "java_demo:${{ env.GIT_TAG }}" .
+          docker tag "java_demo:${{ env.GIT_TAG }}" java_demo:1.0
+        shell: bash
+
+      # - name: Run Trivy vulnerability scanner
+      #   uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
+      #   with:
+      #     image-ref: java_demo:1.0
+      #     format: 'json'
+      #     output: 'trivy-results.json'
+      #     severity: 'CRITICAL,HIGH'
+      - uses: jfrog/setup-jfrog-cli@v3
+        env:
+          # JFrog platform url (for example: https://acme.jfrog.io) 
+          JF_URL: ${{ secrets.JF_URL }}
+          
+          # Basic authentication credentials
+          # JF_USER: ${{ secrets.JF_USER }}
+          # JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
+          # or
+          # JFrog Platform access token
+          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
+      - run: |
+          jf rt ping
+
+          jf docker scan java_demo:1.0
+
+      # - name: Publish report to defectdojo
+      #   id: import-scan
+      #   uses: ivanamat/defectdojo-import-scan@v1
+      #   with:
+      #     token: ${{ secrets.DEFECTOJO_TOKEN }}
+      #     defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
+      #     engagement: ${{ secrets.ENGAGEMENT }}
+      #     product_name: ${{ secrets.PRODUCT_NAME }}
+      #     file: trivy-results.json
+      #     scan_type: Trivy Scan
+      #     test_title: Trivy Scan
+      #     tags: trivy
+      #     skip_duplicates: true
+      #     close_old_findings: true
+      #     push_to_jira: false
+      #     branch_tag: ${{ github.base_ref }}
+      #     build_id: ${{ github.run_id }}
+      #     commit_hash: ${{ github.sha }}
+      # - name: Show response of defectdojo
+      #   run: |
+      #     echo ${{ steps.import-scan.outputs.response }}
 
 #  hawkscan_defectdojo:
 #    name: hawkscan_defectdojo
